### PR TITLE
Enable the RemoteIpValve in the default Tomcat configuration

### PR DESCRIPTION
**Pull request by dmikusa**
It would be nice to have the RemoteIpValve enabled by default, since the Tomcat instance created by the build pack is behind a proxy.  This is not as important with HTTP traffic, but it's important with HTTPS traffic, as without the valve the "HttpServletRequest.isSecure()" method will incorrectly return false.

### CODE REVIEW

**Comment by nebhale** [comment]
@dmikusa-pivotal we'll take a look at this and get it merged, but as a side question how are you terminating HTTPS at the moment?

**Comment by dmikusa** [comment]
Thanks for considering this fix!  

Sorry, I'm not sure I have answer to your side question though.  I'm not sure what part of the CF system is terminating the HTTPS connection.  I just happened to notice that whatever is terminating it is populating the "x-forwarded-*" headers.  Given that, I thought it'd be a good idea to configure the RemoteIpValve.

**Comment by nebhale** [comment]
@dmikusa-pivotal How are you getting the proper SSL certificate provided by the application?  Or are you just using the default one that goes with the default *.cfapps.io domains?

**Comment by nebhale** [comment]
Also, since the values you've chosen for the headers are not the defaults, do you have some sort of documentation as to what they really are?

**Comment by dmikusa** [comment]
Yes, I'm just using the "cfapps.io" domain.  I'm not sure you can use custom SSL certs yet.

  http://support.cloudfoundry.com/entries/24453417-SSL-certificate-for-custom-domain

In regards to the non-default configuration, I found the "x-forwarded" values by looking at the request headers in my app.  I'm not sure the values are document documented (at least I couldn't find them), but I did find a reference to the values on the mailing list.

   https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/2cNU50mf-QI/aVTsXub226sJ

**Comment by nebhale** [comment]
OK, thanks for the input.  At the moment, we'd prefer to hold off on adding this functionality until we've got a better grip on what Cloud Foundry core is doing.  In addition, we'd like a documented contract (so that they don't go changing this stuff beneath us) about these headers.  We've got a planning meeting today to talk about all of this stuff, so please hold tight and we'll get back to you with some more information after we've discussed it.

**Comment by dmikusa** [comment]
Sure, sounds good.

**Comment by nebhale** [comment]
I didn't notice that our meeting was actually moved to tomorrow.  It'll be another day before more info.  Sorry about that.

**Comment by nebhale** [comment]
@dmikusa-pivotal Just an FYI that we're going to get this functionality in, but it'll be a modified version of this pull request.  I'll make sure that the issue is updated when that happens and then we'll close out this request.

**Comment by nebhale** [comment]
@dmikusa-pivotal Can you please test the changes to the buildpack (you'll have to use `--buildpack https://github.com/cloudfoundry/cloudfoundry-buildpack-java` when you push) and let us know if it works for you?  Thanks.

**Comment by dmikusa** [comment]
I tried a push, but it failed with this error.

SEVERE: Parse Fatal Error at line 36 column 48: Element type "Host" must be followed by either attribute specifications, ">" or "/>".
org.xml.sax.SAXParseException; systemId: file:/home/vcap/app/conf/server.xml; lineNumber: 36; columnNumber: 48; Element type "Host" must be followed by either attribute specifications, ">" or "/>".

I think there's a missing space between "appBase" and "unpackWARs".

  appBase="webapps"unpackWARs="true"

**Comment by nebhale** [comment]
Argh, you're right.  Try it now.

**Comment by dmikusa** [comment]
Looks like it's working fine.  When using HTTP or HTTPS, I see the "isSecure" method returning correctly.  Thanks!

**Comment by nebhale** [comment]
OK, I'm going to close this issue then.  Please comment here or open another issue if you notice something amiss later.

**Comment by nebhale** [comment]
@dmikusa-pivotal Just wanted to let you know that this change has now been integrated into Cloud Foundry and should show up on http://run.pivotal.io on the production deployment.

**Pull request closed without merging**
