### PR TITLE
add multi-wars java web application supports

### PR DESCRIPTION
**Pull request by xuf**

### CODE REVIEW

**Comment by xuf** [comment]
@mflu

**Comment by cf-frontend** [comment]
Thanks. Would you mind rebasing, and renaming VCAP_APP_PORT to PORT in your addition? Also, please squash your commits into one.
- @vito 
- @pietern

**Comment by austinbv** [comment]
Hey @xuf, are you planning on continuing with this? If so I think there are only a few things we need before we can merge.
- [ ] Squash Commits
- [ ] Rebase to current master
- [ ] Rename VCAP_APP_PORT to PORT
- [ ] Handle some code quality issues brought up by @mariash 

Thanks for the contribution

**Comment by nebhale** [comment]
@xuf If you're still looking at this, I was wondering if you could give me some insight into why you want to deploy multiple applications to a single container.  What exactly are you attempting to do that cannot be managed as deploying into multiple containers?

**Comment by nebhale** [comment]
Since there has been no response from the author in 3 months, I'm closing this issue.  If it needs to be reopened, please comment.

**Pull request closed without merging**
