### PR TITLE
Support JBoss AS7

### PR DESCRIPTION
**Pull request by mflu**
1. Support JBOSS AS7
2. Support adding more web containers
3. Support detect check with hint file

Missing:
- not to support auto-reconfiguration
- not to support multiple wars (ear package for  jboss)

### CODE REVIEW

**Comment by mflu** [comment]
@figof @anfernee

**Comment by mflu** [comment]
close this for we will put it to another repo

**Comment by mrbrdo** [comment]
@mflu where did you put it? I'd love to have JBoss AS in CF...

**Comment by ndzj081221130** [comment]
@mflu can you support jboss apps now?

**Pull request closed without merging**
